import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Movie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="navbar bg-neutral text-white">
          <Link href={"/"} className="btn btn-ghost normal-case text-xl">
            Next-Movie
          </Link>
        </div>
        <div className="container md:mx-auto mt-7 mb-7 px-5 xl:px-20">{children}</div>
      </body>
    </html>
  );
}
